/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_giaiphuongtrinh_hovanquan_3769;

import javax.swing.JOptionPane;

/**
 *
 * @author Hồ Quân
 */
public class frm_Giaiphuongtrinh extends javax.swing.JFrame {

    /**
     * Creates new form frm_Giaiphuongtrinh
     */
    public frm_Giaiphuongtrinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lb_tieude = new javax.swing.JLabel();
        lb_a = new javax.swing.JLabel();
        txt_a = new javax.swing.JTextField();
        lb_b = new javax.swing.JLabel();
        txt_b = new javax.swing.JTextField();
        lb_c = new javax.swing.JLabel();
        txt_c = new javax.swing.JTextField();
        lb_kq = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_kq = new javax.swing.JTextArea();
        btn_gpt = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ck_bac1 = new javax.swing.JRadioButton();
        ck_bac2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_tieude.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_tieude.setText("GIẢI PHƯƠNG TRÌNH");

        lb_a.setText("Nhập a");

        lb_b.setText("Nhập b");

        lb_c.setText("Nhập c");

        lb_kq.setText("Kết Quả");

        txt_kq.setColumns(20);
        txt_kq.setRows(5);
        jScrollPane1.setViewportView(txt_kq);

        btn_gpt.setText("Giải Phương Trình");
        btn_gpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gptActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        buttonGroup1.add(ck_bac1);
        ck_bac1.setText("Bậc 1");
        ck_bac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_bac1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(ck_bac2);
        ck_bac2.setText("Bậc 2");
        ck_bac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_bac2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ck_bac1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(ck_bac2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ck_bac1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ck_bac2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(lb_tieude))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_kq, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(lb_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_a, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txt_b)
                                    .addComponent(txt_c))
                                .addGap(119, 119, 119)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btn_gpt)
                        .addGap(44, 44, 44)
                        .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lb_tieude, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_a, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_a, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_b, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_b, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_c, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(lb_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_kq, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_gpt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        txt_a.setText("");
        txt_b.setText("");
        txt_c.setText("");
        txt_kq.setText("");
        txt_a.requestFocus();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_gptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gptActionPerformed
        // TODO add your handling code here:
            if(ck_bac1.isSelected()){
                double a = 0;
                double b = 0;
                try {
                    a = Double.parseDouble(txt_a.getText());
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "a nhập sai định dạng");
                    txt_a.selectAll();
                    txt_a.requestFocus();
                }
                try {
                    b = Double.parseDouble(txt_b.getText());
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "b nhập sai định dạng");
                    txt_b.selectAll();
                    txt_b.requestFocus();
                }
                String kq;
                if (a == 0) {
                    if (b == 0) {
                        kq = "Phương trình có vô số nghiệm";
                    } else {
                        kq = "Phương trình vô nghiệm";
                    }
                } else {
                    kq = "Phương trình có một nghiệm x = " + (-b / a);
                }
                txt_kq.setText(kq);
            }
            if(ck_bac2.isSelected()){
                double a = 0;
                double b = 0;
                double c = 0;
            try {
                a = Double.parseDouble(txt_a.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "a nhập sai định dạng");
                txt_a.selectAll();
                txt_a.requestFocus();
            }
            try {
                b = Double.parseDouble(txt_b.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "b nhập sai định dạng");
                txt_b.selectAll();
                txt_b.requestFocus();
            }
            try {
                c = Double.parseDouble(txt_c.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "c nhập sai định dạng");
                txt_c.selectAll();
                txt_c.requestFocus();
            }
            double d = b * b - 4 * a * c;
            String kq = "";
            if (a == 0) {
                if (b == 0) {
                    if (c == 0) {
                        kq = "Phương trình có vô số nghiệm";
                    } else {
                        kq = "Phương trình vô nghiệm";
                    }
                }
            } else {
                if (d > 0) {
                    double x1 = ((-b - Math.sqrt(d)) / (2 * a));
                    double x2 = ((-b + Math.sqrt(d)) / (2 * a));
                    kq = "Phương trình có hai nghiệm phân biệt: " + "x1 = " + x1 + " và x2 = " + x2;
                } else if (d == 0) {
                    kq = "Phương trình có nghiệm kép x1 = x2 = " + (-b / (2 * a));
                } else {
                    kq = "Phương trình vô nghiệm";
                }
            }
            txt_kq.setText(kq + "");
        }
    }//GEN-LAST:event_btn_gptActionPerformed

    private void ck_bac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_bac1ActionPerformed
        // TODO add your handling code here:
        txt_c.setEditable(false);       
    }//GEN-LAST:event_ck_bac1ActionPerformed

    private void ck_bac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_bac2ActionPerformed
        // TODO add your handling code here:
        txt_c.setEditable(true);      
    }//GEN-LAST:event_ck_bac2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Giaiphuongtrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Giaiphuongtrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Giaiphuongtrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Giaiphuongtrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frm_Giaiphuongtrinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gpt;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton ck_bac1;
    private javax.swing.JRadioButton ck_bac2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_a;
    private javax.swing.JLabel lb_b;
    private javax.swing.JLabel lb_c;
    private javax.swing.JLabel lb_kq;
    private javax.swing.JLabel lb_tieude;
    private javax.swing.JTextField txt_a;
    private javax.swing.JTextField txt_b;
    private javax.swing.JTextField txt_c;
    private javax.swing.JTextArea txt_kq;
    // End of variables declaration//GEN-END:variables
}
